version: "2"
services:
  node:
    image: "node:16"
    user: "node"
    working_dir: /var/www/html
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www/html
    ports:
      - "80:3000"
    command: bash -c "npm i && npm run dev" #@TODO: Code pipeline or here?
